cbonsai -p
wal -n -e -i  ~/Pictures/wallpapers/trees.jpg > /dev/null

function show_onefetch() {
     if [ -d .git ]; then
         onefetch
     fi
}
function cd() { builtin cd "$@" && show_onefetch; }

